### PR TITLE
Update to wasmvm 2.2.0-rc.1

### PR DESCRIPTION
**Pull request by chipshort**
Gas changes are because of the patch releases that happened in between 2.1.2 and 2.2.0, not because of 2.2 itself.

### CODE REVIEW

**Comment by faddat** [comment]
I get the same error when building wasmd for v2.1.3

**Comment by faddat** [comment]
* https://github.com/CosmWasm/wasmd/pull/2010 will fix the gas tests here. 

Clearing the cache might fix the strange build issue.  Overall, I recommend moving to github actions.

What was in v2.1.3?

cause phew

* https://github.com/cosmwasgo/cosmwasgo/pull/10

Please note well that tests still fail intermittently with v2.1.3.

I notice that you are not updating this repository to v2.1.3:

is v2.2.0 the actual patch, but state breaking?

**Comment by faddat** [comment]
* https://github.com/CosmWasm/wasmd/pull/2011

nah, this isn't that.

Take the main branch and run the test 20 times.  You will get a pointer error.  Make no code changes to the main branch.

**Comment by chipshort** [comment]
Closing here, since this was superseded by #2012

**Pull request closed without merging**
