### PR TITLE
formatting: gofumpt 

### PR DESCRIPTION
**Pull request by faddat**
This PR should change nothing functionally, but instead nicely organizes the code and makes it easier to read.

It is easy to verify:

```bash
go install mvdan.cc/gofumpt@latest
gofumpt -l -w .
```

### CODE REVIEW

**Comment by alpe** [comment]
Nice one! I like the changes and appreciate your contribution. 🏅 
This touches a lot of files while there are some important feature PRs in progress that cover IBC and statesync. Let's run the  command again when they got merged or after the v0.27.0 final tag at the latest. I will open an issue to keep track of this.

**Comment by ethanfrey** [comment]
Nice addition.

I would like to merge the large outstanding PRs first, before this, to avoid conflicts.
Then happy if you regenerate the cleanup PR and we can merge quickly

**Comment by ethanfrey** [comment]
It would be good to make a Makefile entry (as a separate commit) that does the formatting. So devs can easily run this.

That commit could then easily be cherry-picked once we close most of the other open PRs (to avoid conflicts) and then run it

**Comment by ethanfrey** [comment]
Closing for #851 which adds the commands from the comment to the Makefile.

We will likely need to run that again, but easier to reproduce (and tagged to a fixed version, not latest)

**Pull request closed without merging**
