### PR TITLE
danger zone

### PR DESCRIPTION
**Pull request by faddat**
"hiiiiiiiiighway toooooo the daaaaaaaaaaannnnnnnggeeeeer zone!"

@alpe this PR began as a tweet about a v50 testnet with a live currency, between Simon and I.

But actually I think it will be useful to you guys because there were a few changes in the cmd folder, as often happens.  Those changes are now made :).

### CODE REVIEW

**Comment by alpe** [comment]
Build fails: https://app.circleci.com/pipelines/github/CosmWasm/wasmd/4333/workflows/957615a3-43c2-44a0-a102-983b52efc085/jobs/20054

**Comment by faddat** [comment]
@alpe yeah I think you might actually want to merge this. 

I had to do some of those typical updates from simapp that we frequently see, so it'll probably make it easier to support the final v50 release.  

I'd meant this as more of a placeholder PR but it should be useful to you

**Comment by faddat** [comment]
@alpe you don't want to merge this, sorry.  it uses an ibc with all of the field length patches, not the main branch.

**Comment by faddat** [comment]
* https://github.com/cosmos/ibc-go/pull/4917

**Comment by alpe** [comment]
Thanks for the PR and pushing towards v50 support. The v0.50.1 release was tagged now that we can complete the work. 
I am closing this now in favour of https://github.com/CosmWasm/wasmd/pull/1681 and https://github.com/CosmWasm/wasmd/pull/1696

**Pull request closed without merging**
