### PR TITLE
[DO NOT MERGE] Add check to avoid index out of range panics

### PR DESCRIPTION
**Pull request by pinosu**

### CODE REVIEW

**Review by chipshort — APPROVED** [review]
Check looks good.
Can this happen in practice? Does it make sense to add a test?

**Comment by pinosu** [comment]
@chipshort yes it actually happened in some tests in tgrade. I will add some unit test for it 👍

**Comment by pinosu** [comment]
By double checking I'm not sure anymore if it is supposed to happen or not.  Let's keep it open for now

**Comment by pinosu** [comment]
Closing as not relevant

**Pull request closed without merging**
