### PR TITLE
Gh actions demo (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by gjermundgaraba**

### CODE REVIEW

**Comment by alpe** [comment]
Good start. Where can I see the "Simulation tests" results? I think it did not run.

**Comment by gjermundgaraba** [comment]
Good point @alpe I added a "on: pull-request" to trigger it for this as well for demo purposes

**Comment by alpe** [comment]
I can see the sims run now in github actions [panel](https://github.com/CosmWasm/wasmd/actions/runs/4754732546) ~38min

**Comment by gjermundgaraba** [comment]
Yeah, for the free open source plan machines I guess it might take something like that. It can almost certainly be tweaked with caching to improve it (cosmos SDK team has a bunch of that, I kept it clean for readability). If you pay you could obviously also put heftier machines on it.

**Comment by alpe** [comment]
After #1372 slipped in, I am more in favour of a better structured test output that comes with GH actions. Desmos has an [example](https://github.com/desmos-labs/desmos/blob/master/.github/workflows/sims.yml), too 

What is missing to bring this to main? I guess we can run this in parallel with circleCI for some time

**Comment by gjermundgaraba** [comment]
My thinking would be:
1. identify the pipelines you would want over
2. clean them up a bit
  - maybe a good naming convention
  - how do you want them organized (many actions per pipeline or many smaller pipelines) 
  - make sure the triggers are set for the correct events and branches

So first off, are the ones here the ones you want or would you like more things to run on gh actions?

**Comment by alpe** [comment]
> identify the pipelines you would want over

I think tests -> simulations  would be a good start. Feel free to make a proposal and coordinate with others in the community. Maybe @faddat has an opinion on this. GHA is not really my focus currently.

**Comment by alpe** [comment]
quick heads up: I have been experimenting with some basic GH actions on [mesh-security](https://github.com/osmosis-labs/mesh-security-sdk).

**Comment by alpe** [comment]
Thanks again for your work on this @gjermundgaraba ! 💪 
I think it is fair to challenge the status quo and bring in new ideas. On the other hand there was not much help to make this happen. Closing this now. Follow up discussions should be on the original issue if needed

**Pull request closed without merging**
