### PR TITLE
use latest ibc

### PR DESCRIPTION
**Pull request by faddat**
This updates the rebased sdk50 branch to use the latest ibc-go

### CODE REVIEW

**Comment by faddat** [comment]
@alpe -  this PR basically recreates my earlier one and I'm not too sure why it breaks everything... good. news I guess is that make test runs though.

**Comment by faddat** [comment]
found it :)

**Comment by pinosu** [comment]
@faddat thanks for your contribution! fyi @alpe is on holidays

**Comment by faddat** [comment]
ah very cool, I hope he has a nice time @pinosu :)

FYI, basically in this PR I messed up the bech32 calls in app.go, but I think that'll be sorted tonight.  After that we've got a functional wasmd with eden.

**Comment by faddat** [comment]
closed in favor of #1543

**Pull request closed without merging**
