### PR TITLE
use ecosystem convention for keeper names in app.go

### PR DESCRIPTION
**Pull request by faddat**
This PR changes keeper names in app.go to match the commonly used ecosystem conventional style, which:

* Makes wasmd easier to reference
* Makes upgrading wasmd easier, because there will be fewer merge conflicts

### CODE REVIEW

**Comment by faddat** [comment]
My preference here is to first:

* merge #883 
* merge #866 

The specific reason is that go 1.18 will change some of the supported linters.  We could then dial in on the ones that we think are valuable, and also exclude anything that isn't.

**Comment by alpe** [comment]
Thanks for bringing this up! 🌻 

I have seen public fields in other apps, too. I was always wondering why break encapsulation without a need.
I can see public fields being helpful with the test suite pattern used in sdk and elsewhere. Do you have other examples?

> Makes wasmd easier to reference

what do you mean with this?

**Comment by faddat** [comment]
@alpe - the practice that I openly recommend to other developers when constructing app.go is to very literally copy and paste.

re: encapsulation, and having a standard on these-- I have wondered same as yourself.

**Comment by ethanfrey** [comment]
> from the perspective of someone working on Juno, who'd like to move changes between wasmd and juno, adopting this standard would make upstreaming work into wasmd easier.

I agree :100: with you that we should have a standard and the same format in wasmd, osmosis and Juno.

However, Alex's question was why Juno's approach is better than the wasmd approach. Maybe you or another Juno dev can explain why these are needed to be public. (I have some ideas, but I prefer feedback from actual users)

**Comment by faddat** [comment]
@ethanfrey honestly I don't see a reason in either direction, 🤣

**Comment by faddat** [comment]
OK, this one is ready to rock.  After merging this and #815, the review scope for #863 will drop a great deal.

**Comment by alpe** [comment]
Thanks for the PR and bringing this topic up! I was pending for a while now due to my other priorities but I polished your commits in #951.

**Pull request closed without merging**
