### PR TITLE
Create link to SECURITY.md in other repo

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Review by alpe — COMMENTED** [review]
IMHO it makes sense to keep the `Supported Versions` section here. WDYT?

**Comment by webmaster128** [comment]
Good question. We can also create an overview like this:

Bildschirmfoto 2022-04-11 um 13 19 54

(taken from https://github.com/CosmWasm/advisories#supported-projects-and-version)

If it's not in one place but spread across repos, it will get outdated very quickly.

In https://github.com/CosmWasm/cw-plus/blob/main/SECURITY.md it's structured as link + supported version. But all those supported versions sections seem to be very unrealistic anyways as people build on this software no matter which version name we use for it.

**Comment by webmaster128** [comment]
I brought back the Supported versions section (see last 2 commits). We can try it this way.

**Review by alpe — APPROVED** [review]
LGTM 👏

**Pull request merged**
