### PR TITLE
[WIP] SDK 50 beta 0 upgrade

### PR DESCRIPTION
**Pull request by alpe**
🚧 Early version

After #1528 

Requires compatible IBC Go version to move on

### CODE REVIEW

**Comment by faddat** [comment]
I believe this is no longer blocked.

**Comment by faddat** [comment]
@alpe I'm going to make PR's to `sdk-upgrade50beta0` but please let me know if you'd like them to go to `sdk-upgrade050_rebased2`

**Comment by faddat** [comment]
Summary of PR's:


* #1543 - updates to the latest versions of comsos-sdk and ibc-go
* #1546 - reduces the size of the diff between this and main dramatically

**Comment by alpe** [comment]
Closing in favour of https://github.com/CosmWasm/wasmd/pull/1611

**Pull request closed without merging**
