### PR TITLE
Add Developer's guide and best practices

### LINKED ISSUE #654: Start developer guide for contributors
Document best practices and design decisions. Follow up on #595

### PR DESCRIPTION
**Pull request by pinosu**
Resolves #654

### CODE REVIEW

**Comment by ethanfrey** [comment]
Very cool to see this. I'll let @alpe review and give approval, but great addition

**Review by alpe — APPROVED** [review]
This looks great. A lot to read for newbies. 

I have added some comments where we work differently. Please adjust.

**Comment by dakom** [comment]
Hey.. in the name of "Developer's guide and best practices", can we please have a `Getting Started.md`?

What I mean is a list of steps that gets a new developer up and running with an instance of `wasmd` that they can deploy contracts to.

I'd write it and suggest in the PR, but as of right now I don't know the correct steps. 

A bit of a guess, but something like:

1. `make install` (okay, that _is_ in the Readme)
2. add initial accounts (`wasmd keys` something or other?)
3. create genesis (I am not sure what this is for, if it's necessary, how to do it, and how it relates to wasmd as opposed to other layers of the stack)
4. speed up block time ([something like this?](https://github.com/CosmWasm/wasmd/blob/d5ef3ba2de3c9c87adb2d8826da35f4c5b07bc3c/contrib/relayer-tests/one_chain.sh#L95))

**Comment by dakom** [comment]
I see scripts at https://github.com/CosmWasm/wasmd/tree/main/contrib/local - maybe adapt these into English instructions with some explanation of what's going on (and reduce to bare minimum, i.e. no need to transfer tokens or deploy contracts to get up and running, that's kinda _after_ everything is working)

**Comment by dakom** [comment]
putting that together, my notes, in case it helps:

our chain-id is going to be `localnet`
our gas denomination is going to be configured to `uwasm`
staking denomination is the default `ustake`

adding two users: tester1 and validator1

* `wasmd init localnet --chain-id localnet`
* edit `~/.wasmd/config/app.toml`
  * set `minimum-gas-prices` to `0.025uwasm`
* edit `~/.wasmd/config/client.toml`
  * set `chain-id` to `localnet`
* edit `~/.wasmd/config/config.toml`
  * change all the times to `200ms`
* `wasm keys add tester1`
* wasmd add-genesis-account $(wasmd keys show -a tester1) 10000000000uwasm,10000000000ustake
* `wasm keys add validator1`
* wasmd add-genesis-account $(wasmd keys show -a validator1) 10000000000uwasm,10000000000ustake
* wasmd gentx validator1 "250000000ustake" --chain-id="localnet" --amount="250000000ustake"
* wasmd collect-gentxs

now `wasmd start` should just work

**Comment by ethanfrey** [comment]
> Hey.. in the name of "Developer's guide and best practices", can we please have a `Getting Started.md`?
> 
> What I mean is a list of steps that gets a new developer up and running with an instance of `wasmd` that they can deploy contracts to.
> 
> I'd write it and suggest in the PR, but as of right now I don't know the correct steps.
> 
> A bit of a guess, but something like:
> 
> 1. `make install` (okay, that _is_ in the Readme)
> 2. add initial accounts (`wasmd keys` something or other?)
> 3. create genesis (I am not sure what this is for, if it's necessary, how to do it, and how it relates to wasmd as opposed to other layers of the stack)
> 4. speed up block time ([something like this?](https://github.com/CosmWasm/wasmd/blob/d5ef3ba2de3c9c87adb2d8826da35f4c5b07bc3c/contrib/relayer-tests/one_chain.sh#L95))

A lot of this _should_ be in an overhauled docs site, and definitely info on connecting to chains, setting up Go, etc. But it would be good to have the notes here. Especially things like compiling on MacOS (the ledger warnings/errors), arm64 compatibility, etc.

**Comment by alpe** [comment]
Documentation is an epic were you can always add more or improve it. I think it is important to get something out that we use to iterate and improve.
This document is targeting  **wasmd contributors** as a start. There is a lot more that we need to share with new developers like test strategy and best practices, in order to grow the contributor list in the future. 
Other roles like **contract developers** are not covered here. It is a fair request to have doc for them, too or link to it. 

I have create #1081 to follow up on your request @dakom . Thanks a lot for bringing this up! I would be happy if you can help us building better docs.

**Pull request merged**
