### PR TITLE
ibc-go v3.2.0

### PR DESCRIPTION
**Pull request by faddat**
OK I think this one does it :)

* upgrades ibc-go to v3.2.x

### CODE REVIEW

**Comment by faddat** [comment]
thanks to @joeabbey for the upstream patch that made this work.

**Comment by faddat** [comment]
Hey, as @sacha1337 points out, ibc-go 4.0 is released and compatible with the 45.* series sdk, so I am going to fork this branch, and make a second pr for that.

**Comment by alpe** [comment]
Thanks a lot for your work and this PR! You have been very active to upgrade the dependencies. Please split SDK and IBC upgrades into separate PRs to have a better track of work for people watching this repo and to build the changelog. 🙏 
I will branch from this PR and take core of this to move faster

**Comment by faddat** [comment]
sure, FYI, the SDK and ibc depencencies in this case, were inter-dependent because of the changes in 45.7 :)

(specifically, bumping ibc iirc, though maybe it was both?)

**Comment by alpe** [comment]
Thanks for rebasing the branch!
I have added a "blocked" tag to give everybody some days to discuss this upgrade. 
It is a fresh release and I don't know if it is tested on mainnets well enough. I quickly browsed some other chain releases but could not fine any using v3.2 already.

**Comment by faddat** [comment]
I think that ibc-go v3.2.0 and sdk v45.7 are supposed to go together.

**Comment by alpe** [comment]
Thanks for your help!

**Pull request merged**
