### PR TITLE
Dang/add tokenfactory module

### PR DESCRIPTION
**Pull request by GNaD13**
add module tokenfactory

### CODE REVIEW

**Comment by alpe** [comment]
Thank you for your PR!
This code looks like a version that you copied from [osmosis](https://github.com/osmosis-labs/osmosis/tree/main/x/tokenfactory). 
Although I do understand the demand to have this code available, we should work on a process that includes the Osmosis team as code owners and maintainers.
Please contribute to #911 to discuss and follow up on this.

**Comment by GNaD13** [comment]
> Thank you for your PR! This code looks like a version that you copied from [osmosis](https://github.com/osmosis-labs/osmosis/tree/main/x/tokenfactory). Although I do understand the demand to have this code available, we should work on a process that includes the Osmosis team as code owners and maintainers. Please contribute to #911 to discuss and follow up on this.

Thank you for your reviews! @alpe

**Comment by faddat** [comment]
Hi guys, the osmosis team is well aware that we are using and promoting the token factory code in the ecosystem.

In fact just about everybody that we work with is really keen on this particular pull request

**Comment by alpe** [comment]
@faddat thanks for the additional context! I appreciate the effort and like us to continue the discussion on the issue.
A PR is often pushing a concrete solution while the problem description and motivation can be more inspiring and helpful to come up with different solutions. In this case though it is more about go.mod vs embeding and prioritization of course.

**Pull request closed without merging**
