### PR TITLE
Update changelog for v0.17.0

### PR DESCRIPTION
**Pull request by alpe**
Updates Changelog.md

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
Good start

**Comment by ethanfrey** [comment]
If you are going to tag v0.17.0 now is there anything else you want to put there?
Or is this just to unblock you with the json.RawMessage issue and v0.17.0 rather than 0.16.x as it is technically a breaking API change?

**Comment by alpe** [comment]
I have moved the tasks for v0.17.0 to v0.18.0. This release is for the sdk upgrade and json cast only. Although there are no API changes on our side, it can still have impact when people unmarshal from proto to json. Therefore a v0.17.0 felt more appropriate than v0.16.1.

**Review by ethanfrey — APPROVED** [review]
looks good.

0.17 here we come!

**Pull request merged**
