### PR TITLE
interchain accounts

### PR DESCRIPTION
**Pull request by faddat**
Hi, this PR upgrades wasmd to ibcv3

### CODE REVIEW

**Comment by faddat** [comment]
I think this one is:

* up to date
* ready to go

Could you let me know if this is something that you're interested in reviewing / accepting?

Thanks,

-Jacob

**Comment by ethanfrey** [comment]
Awesome! I was wondering about pulling this out of the 0.46 upgrade and just noticed this PR.
I was off since the end of March, but I will look into this PR this week and give you full feedback

**Comment by ethanfrey** [comment]
Note: Resolves #806

**Review by ethanfrey — COMMENTED** [review]
Thank you for this PR.

I would pull it out into a few different ones. I see:

1. some osmosis-specific stuff that should be removed
2. Renaming lots of WasmApp members to make them public
3. Importing ibcv3 and exposing SetChannel

I see (2) and (3) as independent and not necessarily both needed.

I will try to cut out the ibcv3 commits alone and see if I can make a new PR.

You could also pull out the "make all app members public" code into a separate PR. I have no strong opinion on this either way, but it does make some testing easier. I would like @alpe to give feedback on that part.

**Comment by ethanfrey** [comment]
Closing in favor of #824 and #837

**Pull request closed without merging**
