### PR TITLE
Cosmos-SDK v0.47 integration brach

### LINKED ISSUE #1028: Upgrade to SDK v0.47
Epic to collect and discuss work

### PR DESCRIPTION
**Pull request by alpe**
Resolves #1028 

Time to bring this branch to `main`

🚨 Warning: The sdk version used, includes some key store migration. Make sure you backup your private keys before testing this! You can not switch back to v0.45 afaik

🚨 Warning: Take care that you use the `goleveldb` version used in the SDK. A transitive dependency may change it which caused failing queries on a running server: `Error: rpc error: code = InvalidArgument desc = failed to load state at height 1; version does not exist (latest height: 1): invalid request`
Ensure:
	`github.com/syndtr/goleveldb => github.com/syndtr/goleveldb v1.0.1-0.20210819022825-2ae1ddf74ef7`

🚨 Warning: CometBFT contains breaking [changes](https://github.com/cometbft/cometbft/blob/v0.34.27/CHANGELOG.md#breaking-changes) to Tendermint
🚨  Warning: Use new proto-builder version (Makefile) to let proto types register with the correct registry, [see](https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/UPGRADING.md#protobuf)
🚨 Warning: Ensure that all `ParameterChangeProposal` are completed before the upgrade or migrate them to v1.gov. SDK and wasm modules execute a migration before so that these proposals would not have an affect
	
💡 Info: CLI: `add-genesis-account`, `gentx`,`add-genesis-account`, `collect-gentxs` and others are now under `genesis` command as parent

Follow ups:
- Use v1 gov Messages #1246 
-  Set to final ibc-go tag in go.mod

### CODE REVIEW

**Comment by alpe** [comment]
🚨 Please see https://twitter.com/CosmWasm/status/1620783214125256704

**Comment by faddat** [comment]
hi @alpe would you like me to have the 47 PR I've made, with or without token factory, target this one?

**Comment by dsmello** [comment]
Hello @alpe, Can I help with something to allow us to have the v0.47?

**Comment by alpe** [comment]
@faddat if you want to help with 47, then please do small PRs only with a single purpose. I commented on the [issue](https://github.com/CosmWasm/wasmd/issues/911#issuecomment-1453457927) about token factory.

**Comment by faddat** [comment]
@alpe hey I think I found a bug, I'm going to make note of it, it's in genesis_test.go

**Comment by alpe** [comment]
> hey I think I found a bug

@faddat Thanks for reporting! The re-import must not create an error:
```go
_, err = InitGenesis(dstCtx, dstKeeper, importState)
require.NoError(t, err)
```
I tested with `9ba407c`, `280dc4e`, `7d6a4c1` and it passes. We may have fixed it meanwhile.

**Comment by faddat** [comment]
Weird, I'll double-check and then #1261 is complete :)

**Comment by faddat** [comment]
@pinosu @alpe thanks so much for getting the lint PR in as well as #1265.

That will make this branch way easier to develop, review and use. 

Also, I can now close #1202

**Comment by faddat** [comment]
Hey, I have had a look over this, and I believe that it is good to go. I'm also creating an issue about what I believe is called conformance testing, but I'm not certain I even have the correct name for the type of testing that I'm interested in either adding or seeing added to WASMD.

Basically when looking through the test, the thing that I believe is missing is something that attempts to do as many random things as possible with contracts in an effort to find bugs. Overall I think that that tests here are really very rigorous and it's one of the more pleasant parts of working with WASMD, because I believe that we would catch most things. So if it's cool with you, what I'm going to do is I'm going to approve this, and I'm going to create an issue describing a class of tests that I'm interested in for this code.

**Review by faddat — APPROVED** [review]

**Review by faddat — COMMENTED** [review]
waiting on the removal of propsal types and will re-review then

**Comment by alpe** [comment]
@faddat thanks for the review!

There are quite some changes in the PR. I will keep it open for more feedback and merge on Monday. #1269 is not blocking this and will land in main shortly afterwards.

**Comment by faddat** [comment]
@alpe thanks so much for the work you out into this one.  I like the state of the release a lot.

**Review by faddat — APPROVED** [review]

**Review by pinosu — APPROVED** [review]
Great job! 💯

**Comment by faddat** [comment]
thanks to you too @pinosu

**Pull request merged**
