### PR TITLE
Upgrade to cosmos-sdk 0.46

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #927 

- [x] fix app build
- [ ] fix unit tests

### CODE REVIEW

**Comment by faddat** [comment]
Hi Yihuang, thanks a ton!

I suspect I may be able to fix your branch.

**Comment by yihuang** [comment]
> Hi Yihuang, thanks a ton!
> 
> I suspect I may be able to fix your branch.

please feel free to, we will probably release sdk-0.46 without wasmd first.

**Comment by faddat** [comment]
I just reviewed and it is very similar to ours.  I'll see if I can make it work, I think some of the changes in my 457 branch actually solved tests for 46.

**Comment by faddat** [comment]
Here's where I'd upgrade from: #937

**Comment by alpe** [comment]
I am closing this now as this the oldest v046 branch. Thank you for your contribution! 👍

**Pull request closed without merging**
