### PR TITLE
Cosmos SDK v46

### PR DESCRIPTION
**Pull request by faddat**
Hi, so here's another CW for 46.

I am mainly interested in seeing how much better or worse we can get CW-enabled chains to run in high traffic scenarios.

I think this contributed to the fall of terra.  

After some debugging and refinement, hope to get this out on Juno and Osmosis.

### CODE REVIEW

**Comment by ethanfrey** [comment]
A basic question.
Why would 0.46 have considerably better performance than 0.45?

most overhead is storage iirc, and smt hasn't landed in 0.46 yet, right? very curious as to any performance benchmarks

**Comment by faddat** [comment]
@ethanfrey the tendermint team tells me that 35 is a good deal better.

But honestly, I don't know yet, and need to do some more work on this patch, too.

**Comment by ethanfrey** [comment]
I agree tendermint is far better.

But bottleneck is app afaik and there was no significant improvement there I believe. 

you can make the experiment, we are holding off 0.46 for a while and recommend other chains to as well

**Comment by faddat** [comment]
Thanks ethan!

would you mind explaining into the bottleneck itself some?

just for example I am super confidence but no i cannot present data and no I'm not gonna gather the data -- that performance issues were used in the mainly financial attack on Terra.  

Really I've quite high confidence on this, based on my personal observations during the attack. 

So basically I've got a goal of getting CW + cosmos sdk as tightly in sync, release-wise, as possible. 

I think it's now an integral part of the cosmos stack overall.

**Comment by faddat** [comment]
@ethanfrey having just read the PR to revert middleware, I must admit sir, that is a very good point.

**Comment by faddat** [comment]
Hey this is going to require significant rework and is blocked here:

https://github.com/cosmos/cosmos-sdk/pull/11985

We (craft team) have decided (much debate) to eat this one and proceed with the 46 upgrade.

**Comment by faddat** [comment]
This was step one of the rework:

https://github.com/cosmos/ibc-go/pull/1412

**Comment by faddat** [comment]
This is now pretty much complete but we need to fix the snapshots.

**Comment by faddat** [comment]
@catShaark put in a PR to the sdk that fixes snapshots.  This should be working shortly.

**Comment by ccamel** [comment]
@faddat Any news on this one? We're waiting this for some features of COSMOS SDK v0.46. 🙏 

I can help if needed. Thank you!

**Comment by faddat** [comment]
:D hey, so this has been on hold for this PR:

[f68653f](https://github.com/cosmos/cosmos-sdk/pull/12221/commits/f68653f13648a873f600d676a20af3b79bdbe791)

but that's looking done now, so I am going to try and update this now.

**Comment by faddat** [comment]
Related:

https://github.com/cosmos/ibc-go/pull/1653/

**Comment by faddat** [comment]
46 isn't released, but we'll probably start to use this on testnets, so I'm marking this r4r.

Thanks to everyone buildin' cw!

<3

**Comment by faddat** [comment]
Note: https://github.com/cosmos/cosmos-sdk/pull/12458

**Comment by faddat** [comment]
<3 @vuong177

**Comment by RafilxTenfen** [comment]
@faddat why did you closed?

**Pull request closed without merging**
