### PR TITLE
lint main branch

### PR DESCRIPTION
**Pull request by faddat**
This PR lints the main branch more strictly.

* revive has all options turned on
* linting fixes from develop_47 have been improved upon

### CODE REVIEW

**Comment by alpe** [comment]
Thanks but why would we need this with #1149 merged to main today? I would expect this to create conflicts only.

**Comment by faddat** [comment]
mainly thinking about past versions.  I also made a conflict cleaning PR, #1274

**Comment by faddat** [comment]
Didn't wanna bring ya merge conflicts.  Actually, when we are both done shipping like wild, I'd really like to talk with you about branching in this repo.

**Comment by alpe** [comment]
When #1149 is merged to main, all development will continue on main again. There will be a maintenance branch for security fixes on the sdk45 series for some time but no backport of features planned.
The branch will be called `releases/v0.3x`. The first version with 47 support will be `v0.40.0`

**Pull request closed without merging**
