### PR TITLE
wasmd v0.29.2 and SDK v0.46.6 and IBC v5.1.0

### PR DESCRIPTION
**Pull request by faddat**
# Funded by Juno, built by Notional

**wasmd for the SDK 46 series:**
* ibc-go v5.2.0
* tendermint v0.34.24
* cosmos sdk v0.46.6
* interchain-accounts v0.32.1+dragonberry patch
* iavl v0.19.4
* wasmd v0.29.2

## NOTICE 
Some somewhat conflicting information about the status of cosmos-sdk v0.46.* was released on the cosmos hub forum, here:

https://forum.cosmos.network/t/ibc-security-advisory-dragonberry/7702

Later discussions with the SDK team and Umee revealed that a patch was underway.  Notional will continue to maintain this branch so that users of sdk 46 are able to work with security. 

Given that this branch has active users that want to make chain happen, we're going to try to restore it to its former glory, specifically, it should pass 100% of the tests.

I am iffy on all of this, but it ought to be 1-3 days work to ensure that this branch works again.  When it passes all tests, I will remove the below warning.  Notional will continue to work on SDK v47 support for:

* ibc-go
* interchain-accounts-demo
* wasmd

## Guidance

THis commit hash [b385d2d](https://github.com/CosmWasm/wasmd/pull/938/commits/b385d2d709695e5bda454ee4f5bd026702fc4f91)

corresponds to the last known fully good happy version, and it also corresponds to v0.29.1 in main. 

# Funded by Juno built by Notional

### CODE REVIEW

**Comment by faddat** [comment]
@vuong177 🔥

**Comment by faddat** [comment]
@vuong177 I think you've hit an ibc-go bug.  If you look at ibc-go v3.2.0, you'll see a commit from @joeabbey.

His most recent commit fixes something something sequence numbers, and by doing that, also fixes the reflect test.

**Comment by faddat** [comment]
@vuong177 I checked, and the commit that we're using here, is up to date with the latest commit from ibc-go, so it might not be that....

**Comment by vuong177** [comment]
yep, seem have problem with router

**Comment by faddat** [comment]
Great progress!

**Comment by faddat** [comment]
I have the most terrible idea ever

prepare yourself

**Comment by faddat** [comment]
oh

Nevermind my terrible idea!

I headed to the store and you conquered the thing!

Thanks Vuong!

**Comment by faddat** [comment]
Thanks Vuong!

**Comment by faddat** [comment]
@vuong177 hey, when you did the proposal integration tests, there's a difference between how it was done before and how it's done now-- @alpe could you have a look?

Basically if we look at the proposal integration tests, I think we should be checking the storedPropsal, but we check src.  This is kinda a very rough spot re: the gov changes in 46 and long term it may make the most sense to refactor to use govv1-- or just @jakehartnell make a gov that does not depend on the sdk using daodao.

**Comment by faddat** [comment]
to anyone using this branch:

to the best of our knowledge, it is fully working.

No guarantees, and PR's to fix the last of the tests are super appreciated.

**Comment by 0fatih** [comment]
Hey @faddat! First of all, thank you very much for your efforts. With your branch, I was able to start my blockchain.

Is there anything I can do to merge your PR to the main repo?

**Comment by 0fatih** [comment]
Can we change the expected spend gas directly for the first error?

```
expected: 0x1964f
actual  : 0x1a455
```

**Comment by alpe** [comment]
To move this forward, I think #1022 is ahead of this PR already. 

There was no decision made for IBC v4 or v5: https://github.com/CosmWasm/wasmd/issues/960
@ everybody: please contribute to the discussions rather than pushing a solution
See also https://github.com/CosmWasm/wasmd/issues/941#issuecomment-1260547555

**Comment by faddat** [comment]
@alpe tbh sir, if there's a problem here, it is the lack of decision. 

* #1022 will require a good deal more work to complete, I need to ensure that it no longer imports simapp.

**Comment by faddat** [comment]
@0fatih please note that I just found a bug in the icakeeper implementation here.

**Comment by faddat** [comment]
Hey guys, I have to resolve the conflicts here and when I do that there was some trouble, so please know that this is not yet 0.29.0 but working on making that happen

**Comment by faddat** [comment]
Again, I don't recommend that you use this work.

## Path forward for current users:

* Help to upgrade ibc-go:  https://github.com/cosmos/ibc-go/pull/2500
* Help to upgrade interchain-accounts-demo: https://github.com/cosmos/interchain-accounts-demo/pull/135

Once those are done, we can begin work to upgrade wasmd.

**Comment by faddat** [comment]
THis commit hash [b385d2d](https://github.com/CosmWasm/wasmd/pull/938/commits/b385d2d709695e5bda454ee4f5bd026702fc4f91)

corresponds to the last known fully good happy version.

**Comment by faddat** [comment]
NB: this is v0.29.2 + needed adaptations for 46

**Comment by MSNTCS** [comment]
@faddat nice job. is there any timeline for merging this?

**Comment by faddat** [comment]
Important Notes on SDK v0.47.x work and information on how we see items like this branch:

* https://github.com/cosmos/ibc-go/pull/2889

**Comment by alpe** [comment]
You have 2 branches open for SDK v0.46. Can this be closed in favour of #1126? Or the other way?

**Comment by faddat** [comment]
Yeah, I think that makes sense.  No one building, should make a chain with this one.  Thanks!

**Pull request closed without merging**
