### PR TITLE
Add amino annotations to proto

### LINKED ISSUE #1157: new proto annotations
We have new code upstream in the cosmos-sdk that will allows adding `option (amino.name)` to `messages` which will enable automated amino encoders, and a bunch of other codegen features. In the future will automate registration of amino interfaces as well.

[This PR](https://github.com/cosmos/cosmos-sdk/pull/13501) added amino annotations for codegen.
[This is the original issue](https://github.com/cosmos/cosmos-sdk/issues/13407)

If we don't want to take the entire PR, I suggest we at least [add this proto file](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino)

cc @faddat @amaurym

### PR DESCRIPTION
**Pull request by alpe**
Resolves #1157 

@pyramation please review: the failing tests/ linter/ simulations runs can be ignored as this stage. I am going to rebase the branch later. I am more interested if this PR includes all the annotations that you need

### CODE REVIEW

**Comment by alpe** [comment]
@mergify: rebase

**Comment by alpe** [comment]
@Mergifyio rebase

**Comment by pyramation** [comment]
LGTM!

**Review by pyramation — APPROVED** [review]

**Comment by alpe** [comment]
No backport as amino.proto was introduced > sdk 45

**Pull request merged**
