### PR TITLE
Integrate contract migrations

### LINKED ISSUE #121: Wire up real migration to wasmd with integration test
Depends on https://github.com/CosmWasm/wasmd/issues/118 and https://github.com/CosmWasm/go-cosmwasm/issues/93

Now that `migrate` is exposed by go-cosmwasm, call that from the `wasmd` code. Add an integration test (like staking and reflect) that ensures this works properly with a real migration. (The test should be there with stubs, be needs to be updated fro the real full-stack experience)

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #121 

This updates to use the real cosmwasm contract migration code. This breaks the existing migration tests that rely on the stubs.

We should fix up the tests and ensure they work. In addition to hackatom self-upgrades, there is a burner contract that will delete all state and release any tokens owned by the contract to a provided address (aka self-destruct in ethereum world)

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by ethanfrey** [comment]
@alpe this is a start for the migration integration. You can gladly build on this and take over the PR. If you have no time, then I will do it.

The supported migration messages are:

`contract.wasm` (default) can do a self-upgrade to change the verifier

```rust
pub struct MigrateMsg {
    pub verifier: HumanAddr,
}
```

```json
{ "verifier": "cosmos164l0ge46x5ndx8gtnqtna7wm2tujnz49pdk0ef"}
```

The `burner.wasm` contract can never be instantiated directly. It can only be used as a migration from an existing contract. You can set up a hackatom contract with some funds, then burn it. The supported migration message is:

```rust
pub struct MigrateMsg {
    pub payout: HumanAddr,
}
```

```json
{ "payout": "cosmos164l0ge46x5ndx8gtnqtna7wm2tujnz49pdk0ef"}
```

To fully test this, it returns two log messages (`action=burn` and `payout=<addr>`), a SendMsg to transfer the funds in the previous contract to the payout address, and a data field `[]byte("burnt")`. You can ensure the balances were properly updated (dispatchMsgs worked) and the log and data messages were visible in the result returned from migrate to ensure everything is handled correctly.

**Comment by alpe** [comment]
I have added #140 for the tests to be merged into this branch.

**Comment by ethanfrey** [comment]
Thanks for finishing this Alex. Looks good.

**Comment by ethanfrey** [comment]
Merging regardless of failing docker image (some http timeout)

**Pull request merged**
