### PR TITLE
Research: wazerod

### PR DESCRIPTION
**Pull request by faddat**
Hey I wanted to share with confio and the larger CW community, some research that I have been attempting.

You probably don't want to review this for merge, it's really not ready for that yet.

However, you might, if you find the concept interesting, want to review it.

This template branch is a beginning of an attempt to eliminate dependencies on CGO in WASMD & wasmvm.

As a side effect, it would eliminate the wasmvm repository. 

You will also find notes interspersed throughout the code, on places where I think that CGO is harmful.

I'm working on this in a couple of branches, and I'm about to make a merge of one of them to the branch that represents this PR, and you can find more information on the research here:

https://hackmd.io/@xklVAbyuQ9m2DFWqzADekw/B19vvqhuh

## current state

Right now this has combined wasmvm and WASMD, and has not yet implemented wazero.  

There are a number of open questions that have been outlined in the hackmd above.

## foundation of thought 

* https://www.cockroachlabs.com/blog/pebble-rocksdb-kv-store/

### CODE REVIEW

**Comment by alpe** [comment]
Thanks for sharing. Please note that we have very limited capacity and focusing on the sdk 50 upgrade and mesh security. 
I have added the spike label to this PR

**Comment by faddat** [comment]
@alpe makes perfect sense, this would certainly be a spike.

**Comment by alpe** [comment]
@faddat can we close this now?

**Comment by faddat** [comment]
Hey @webmaster128 Thanks for keeping this here as long as you did.  I do indeed think it is quite safe to close now.

Makes more sense to check out wasmvm 2.0 instead of reinventing the wheel....

**Pull request closed without merging**
