### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by alpe**
* Latest from sdk 47 development branch: https://github.com/cosmos/cosmos-sdk/tree/release/v0.47.x
* Lastest from ibc-go main branch (that supports v7): https://github.com/cosmos/ibc-go
* Use informal fork for tendermint and other pinned versions from sdk go.mod
* Remove ibc channel hack

### CODE REVIEW

**Comment by alpe** [comment]
@mergifyio rebase

**Comment by alpe** [comment]
@sahith-narahari I was surprised to see you push --force on my branch.  If mergify broke something, I would appreciate a comment instead. We practice branch ownership to be on the safe side.

**Comment by sahith-narahari** [comment]
hi @alpe, this push was not done from my side. I'm looking into how it happened, will let you know once I have more details. Sorry for the noise and any inconvienece caused

**Comment by alpe** [comment]
@sahith-narahari oh, it was mergify. I am very sorry to blame you. 
> This pull request got rebased on behalf of a random user of the organization.

**Pull request merged**
